steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-rag-app:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-rag-app:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-rag-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-rag-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '120s'
      - '--set-env-vars'
      - 'PINECONE_API_KEY=${_PINECONE_API_KEY},OPENROUTER_API_KEY=${_OPENROUTER_API_KEY},SECRET_KEY=${_SECRET_KEY},GITHUB_REPO_URL=${_GITHUB_REPO_URL}'

images:
  - 'gcr.io/$PROJECT_ID/flask-rag-app:$COMMIT_SHA'

substitutions:
  _PINECONE_API_KEY: ''
  _OPENROUTER_API_KEY: ''
  _SECRET_KEY: ''
  _GITHUB_REPO_URL: ''