name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml \
          --substitutions="_PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }},_OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }},_SECRET_KEY=${{ secrets.SECRET_KEY }},_GITHUB_REPO_URL=${{ secrets.GITHUB_REPO_URL }}"